name: ğŸš€ Deploy
on:
  push:
    branches:
      - main
  pull_request: {}

jobs:
  deploy:
    name: ğŸš€ Deploy
    runs-on: self-hosted
    # only build/deploy main branch on pushes
    if: ${{ github.ref == 'refs/heads/main' && github.event_name == 'push' }}

    steps:
      - name: â¬‡ï¸  Checkout repo
        uses: actions/checkout@v2

      - name: ğŸ” Apply secrets env
        run: |
          echo 'PORT=5001' > .env
          echo 'DATABASE_URL="file:./prod.db"' >> .env
          echo 'SESSION_SECRET="${{secrets.SESSION_SECRET}}"' >> .env

      - name: âš’ Install and build
        run: |
          yarn install
          PORT=5001 yarn build
          yarn prisma db push

      - name: ğŸ§‘â€ğŸ”§ Setup
        run:

      - name: ğŸš€ Deploy
        run: |
          chown -R plone:plone *
          su plone
          sudo -u plone pm2 startOrRestart ecosystem.config.js
