name: ğŸš€ Deploy
on:
  push:
    branches:
      - main
  pull_request: {}

jobs:
  deploy:
    name: ğŸš€ Deploy
    runs-on: self-hosted
    # only build/deploy main branch on pushes
    if: ${{ github.ref == 'refs/heads/main' && github.event_name == 'push' }}

    steps:
      - name: â¬‡ï¸  Checkout repo
        uses: actions/checkout@v2

      - name: Apply secret env
        run: |
          echo 'DATABASE_URL="file:./prod.db"' > .env
          echo 'SESSION_SECRET="${{secrets.SESSION_SECRET}}"' >> .env

      - name: âš’ Install dependencies and build
        run: yarn install && yarn build

      - name: ğŸš€ Deploy
        run: pm2 startOrRestart ecosystem.config.js
